title: "DiCoSTEM-TT"
description: "Competencia Digital y Educaci贸n STEM en la Formaci贸n del Profesorado"
claim:
  es: "Competencia Digital y Educaci贸n STEM en la Formaci贸n del Profesorado"
  en: "Digital Competence and STEM Education in Teacher Training"
url: "https://dicostem-tt.github.io"
baseurl: ""  # keep empty for organization/user pages
lang: es
languages: ["es","en"]
timezone: Europe/Madrid

theme: null
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: page
      image: /assets/img/social-card.png
  - scope:
      path: "en"
    values:
      lang: en
  - scope:
      path: "es"
    values:
      lang: es

exclude:
  - "README.md"
  - "node_modules"
  - "package.json"
  - "package-lock.json"

permalink: pretty

# SEO & social
social:
  name: "DiCoSTEM-TT"
  links: []
