# Configuración del sitio
title: "DiCoSTEM-TT"
tagline: "Competencia Digital y Educación STEM en Formación del Profesorado"
description: "Un proyecto de 4 años para diseñar, implementar y evaluar un programa metacognitivo y multidimensional que desarrolle la competencia digital y los laboratorios virtuales STEM en la formación inicial del profesorado."

# Configuración de Jekyll
url: https://dicostem-tt.github.io
baseurl: ""

# Configuración del idioma
lang: es

# Configuración de construcción
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Excluir archivos del sitio generado
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Información adicional
author: "Equipo DiCoSTEM-TT"
email: "naranjo@unex.es"

# Configuración de SEO
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      lang: "es"

collections:
  results:
    output: true
  resources:
    output: true
