title: DiCoSTEM-TT
description: Digital Competence and STEM Education in Teacher Training
url: https://dicostem-tt.github.io
baseurl: ""
lang: en
permalink: pretty

theme: jekyll-theme-minimal
remote_theme: just-the-docs/just-the-docs

just_the_docs:
  logo: "/assets/img/logo_dicostem.svg"
  search_enabled: true
  nav_external_links:
    - title: Español
      url: /es/
    - title: GitHub
      url: https://github.com/DiCoSTEM-TT/DiCoSTEM-TT

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

collections:
  results:
    output: true
  resources:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
